{
    "features": {
        "rest": {
            "channelCreate": "yes",
            "channelDelete": "yes",
            "channelDM": "partial",
            "channelEdit": "yes",
            "channelHistory": "partial",
            "channelInfo": "yes",
            "channelPermission": "partial",
            "editProfile": "yes",
            "inviteCreate": "no",
            "inviteDelete": "no",
            "inviteInfo": "yes",
            "inviteJoin": "yes",
            "messageDelete": "yes",
            "messageEdit": "yes",
            "messageSend": "yes",
            "messageSendFile": "no",
            "roleCreate": "no",
            "roleDelete": "no",
            "roleEdit": "no",
            "roleInfo": "yes",
            "sendTyping": "yes",
            "serverBan": "yes",
            "serverBans": "yes",
            "serverCreate": "yes",
            "serverDelete": "yes",
            "serverEdit": "yes",
            "serverInfo": "yes",
            "serverKick": "yes",
            "serverUnban": "yes",
            "transferOwnership": "no",
            "voiceMove": "no"
        },
        "ws": {
            "channelCreate": "yes",
            "channelDelete": "yes",
            "channelUpdate": "yes",
            "messageDelete": "yes",
            "messageReceive": "yes",
            "messageUpdate": "yes",
            "roleCreate": "yes",
            "roleDelete": "yes",
            "roleUpdate": "yes",
            "presenceReceive": "yes",
            "presenceSend": "yes",
            "serverBan": "yes",
            "serverCreate": "yes",
            "serverDelete": "yes",
            "serverUnban": "yes",
            "serverUpdate": "yes",
            "typing": "yes",
            "userJoin": "yes",
            "userLeave": "yes",
            "voiceMultiServer": "no",
            "voiceReceive": "no",
            "voiceSend": "no",
            "voiceStateUpdate": "no"
        }
    },
    "name": "Discordia",
    "language": "Lua",
    "github": "SinisterRectus/Discordia",
    "description": "Discord API library written in Lua for the Luvit framework"
}
